"use strict";
const $=(q,e=document)=>e.querySelector(q), screen=$("#screen"), levelText=$("#levelText"), progressBar=$("#progressBar"), statusEl=$("#lives");
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), rand=(a,b)=>Math.random()*(b-a)+a;
let level=clamp(Number(localStorage.getItem("deb27-level"))||1,1,27), cleanup=()=>{}, locked=false;
const DEB_FACE='<img class="face-sprite" src="assets/deb.jpeg" alt="Deb">';
const LEVELS=[
 ["Fuga dall’asilo","🧸","Schiva le tre insegnanti per 6 secondi.","escape",{}],
 ["Corsa verso il cancello","🏁","Tocca veloce per raggiungere il cancello.","race",{icon:"👧🏻"}],
 ["Pattini nell’ufficio","🛼","Slalom tra le scrivanie senza scontri.","dodge",{actor:"🛼",hazards:["🗄️","🪑","📠"]}],
 ["Stelle sui pattini","⭐","Raccogli 5 stelle: durano solo 0,7 secondi!","collect",{actor:DEB_FACE,item:"⭐",count:5,ttl:700}],
 ["No fruit zone","🥦","Schiva frutta e verdura. Ovviamente.","dodge",{actor:DEB_FACE,hazards:["🍎","🥦","🥕","🍌"]}],
 ["Veggie invasion","🥕","Elimina 7 intrusi vegetali.","tap",{items:["🥦","🥕","🍅"],count:7}],
 ["Destination: Cambridge","🇬🇧","Raggiungi Cambridge senza farti prendere dai gabbiani.","flight",{}],
 ["Three weeks of English","💬","Scegli la traduzione corretta. Very British.","english",{}],
 ["Casa al mare","🏠","Trascina le piastrelle nelle sagome.","collect",{actor:DEB_FACE,item:"🔷",count:4}],
 ["Piastrella perfetta","📐","Tocca quando l’indicatore è al centro.","timing",{}],
 ["Atterraggio","🤸🏻‍♀️","Ferma il salto nella zona perfetta.","timing",{}],
 ["Sulla trave","⚖️","Mantieni Deb in equilibrio per 4 secondi.","balance",{}],
 ["Anno 18: incontro","✨","Fai incontrare Deb e Jurgen.","drag",{a:"👩🏻",t:"🧑🏻"}],
 ["Heart combo","💖","Raccogli 6 cuori. A wild Jurgen appeared.","collect",{actor:"🧑🏻‍🤝‍👩🏻",item:"💖",count:6}],
 ["Trova Lapo","🐶","Scopri Lapo tra le carte.","find",{target:"🐶",others:["🧸","🦊","🐻","🐼","🐨"]}],
 ["Trova Milù","🐱","La regina dei nascondigli.","find",{target:"🐱",others:["📦","🧶","🛋️","🪴","👢"]}],
 ["Puma torna a casa","🐕","Porta Puma da Deb e Jurgen.","maze",{}],
 ["Puma turbo","🦴","Raccogli 5 ossi con Puma.","collect",{actor:"🐕",item:"🦴",count:5}],
 ["Pag","🌊","Acchiappa il sole dell’isola.","tap",{items:["☀️"],count:5}],
 ["Corfù","⛵","Naviga fino alla baia.","drag",{a:"⛵",t:"🏝️"}],
 ["Mykonos","💨","Tocca i mulini per farli girare.","tap",{items:["🌬️"],count:6}],
 ["Santorini","🤍","Raccogli le cupole blu.","collect",{actor:DEB_FACE,item:"🔵",count:5}],
 ["Albania → Cuba","🗺️","Trova la rotta fra i due mondi.","memory",{pairs:["🇦🇱","⛰️","🇨🇺","🎶","🌊","🏖️"]}],
 ["Madagascar","🦎","Scova 5 lemuri nella giungla.","tap",{items:["🐒"],count:5}],
 ["Maldive","🐠","Nuota tra i pesci tropicali.","dodge",{actor:"🤿",hazards:["🐠","🐡","🪸"]}],
 ["Aurora","🌅","Raccogli le stelle per scoprire il personaggio migliore.","aurora",{}],
 ["Final Boss: Life Mix","👾","Sconfiggi il caos: evita verdure, prendi cuori!","boss",{}]
];
const quips={1:"Containment failed.",5:"Vegetables successfully rejected.",9:"Unpaid construction worker unlocked.",13:"A wild Jurgen appeared.",18:"Puma joined the party.",26:"Best character unlocked: Aurora."};
function setLevelUI(){levelText.textContent=`LEVEL ${level} / 27`;progressBar.style.width=`${level/27*100}%`;statusEl.textContent="READY"}
function menu(){cleanup();locked=false;screen.innerHTML=$("#menuTemplate").innerHTML;levelText.textContent="DEB: LEVEL 27";progressBar.style.width=`${level/27*100}%`;statusEl.textContent=level>1?`${level-1} CLEARED`:"READY";$("[data-action=start]").textContent=level>1?`CONTINUE — LEVEL ${level}`:"PRESS START"}
function render(){cleanup();locked=false;setLevelUI();const [title,icon,instruction,type,cfg]=LEVELS[level-1];screen.innerHTML=`<div class="level-card"><div class="level-icon">${icon}</div><h2>${title}</h2><p class="instruction">${instruction}</p><div class="arena"><b class="score">0</b></div></div>`;const arena=$(".arena"); requestAnimationFrame(()=>games[type](arena,cfg||{}))}
function complete(){if(locked)return;locked=true;cleanup();navigator.vibrate?.(40);if(level===27){localStorage.setItem("deb27-level","27");return finale()}const done=level;level++;localStorage.setItem("deb27-level",String(level));screen.innerHTML=`<div class="result-card"><div class="stamp">✓</div><p class="eyebrow">LEVEL ${done} CLEARED</p><h2>${quips[done]||"Checkpoint unlocked."}</h2><p>${LEVELS[done]?.[0]||"Prossimo livello: boss mode."}</p><button class="primary" data-next>CONTINUE</button></div>`;$("[data-next]").onclick=render;setLevelUI()}
function fail(msg="Quasi! Riprova subito."){if(locked)return;locked=true;navigator.vibrate?.([30,30,30]);screen.insertAdjacentHTML("beforeend",`<div class="toast">${msg}</div>`);setTimeout(render,700)}
function pos(e,a){const r=a.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:p.clientX-r.left,y:p.clientY-r.top}}
const games={
 escape(a){let playerX=45,teachers=[],raf,last=0,start=performance.now();a.innerHTML+=`<div class="actor photo-actor" style="left:45%;bottom:7%">${DEB_FACE}</div>`;const player=$(".actor",a);const move=e=>{playerX=clamp(pos(e,a).x/a.clientWidth*100,5,84)};a.addEventListener("pointermove",move);a.addEventListener("pointerdown",move);const loop=t=>{player.style.left=playerX+"%";if(teachers.length<3&&t-last>650){last=t;const h=document.createElement("div");h.className="hazard teacher";h.textContent="👩🏻‍🏫";h.x=[12,45,78][teachers.length];h.y=-55;h.style.left=h.x+"%";a.append(h);teachers.push(h)}for(const h of teachers){const target=playerX-h.x;h.x+=clamp(target,-.45,.45);h.y+=2.1;h.style.left=h.x+"%";h.style.top=h.y+"px";const r=h.getBoundingClientRect(),q=player.getBoundingClientRect();if(r.left<q.right-8&&r.right>q.left+8&&r.top<q.bottom&&r.bottom>q.top)return fail("Presa! La fuga riparte subito.");if(h.y>a.clientHeight){h.y=-55;h.x=rand(5,85)}}const elapsed=(t-start)/1000;$(".score",a).textContent=`${Math.min(6,elapsed).toFixed(1)} / 6s`;if(elapsed>=6)return complete();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);cleanup=()=>{cancelAnimationFrame(raf);a.removeEventListener("pointermove",move);a.removeEventListener("pointerdown",move)}},
 drag(a,c){a.innerHTML+=`<div class="target" style="right:8%;top:15%">${c.t}</div><div class="actor" style="left:8%;bottom:12%">${c.a}</div>`;const x=$(".actor",a),t=$(".target",a);const move=e=>{e.preventDefault();const p=pos(e,a);x.style.left=`${clamp(p.x-27,0,a.clientWidth-54)}px`;x.style.top=`${clamp(p.y-27,0,a.clientHeight-54)}px`;const r=x.getBoundingClientRect(),q=t.getBoundingClientRect();if(r.left<q.right&&r.right>q.left&&r.top<q.bottom&&r.bottom>q.top)complete()};a.addEventListener("pointermove",move);a.addEventListener("pointerdown",move);cleanup=()=>{a.removeEventListener("pointermove",move);a.removeEventListener("pointerdown",move)}},
 race(a,c){a.innerHTML+=`<div class="lane"></div><div class="runner">${c.icon}</div><div class="finish">🚪</div>`;let n=0,last=0;const tap=()=>{const now=Date.now();if(now-last<65)return;last=now;n++;$(".score",a).textContent=`${n}/12`;$(".runner",a).style.left=`${8+n*6}%`;if(n>=12)complete()};a.addEventListener("pointerdown",tap);cleanup=()=>a.removeEventListener("pointerdown",tap)},
 tap(a,c){let n=0,timer;const spawn=()=>{if(locked)return;const b=document.createElement("button");b.className="tap-target";b.textContent=c.items[Math.floor(Math.random()*c.items.length)];b.style.left=`${rand(8,78)}%`;b.style.top=`${rand(12,75)}%`;b.onclick=()=>{b.remove();n++;$(".score",a).textContent=`${n}/${c.count}`;navigator.vibrate?.(12);if(n>=c.count)complete();else spawn()};a.append(b);timer=setTimeout(()=>{b.remove();spawn()},1300)};spawn();cleanup=()=>clearTimeout(timer)},
 collect(a,c){let n=0,item,itemTimer;a.innerHTML+=`<div class="actor" style="left:8%;bottom:10%">${c.actor}</div>`;const actor=$(".actor",a);const spawn=()=>{clearTimeout(itemTimer);item?.remove();item=document.createElement("div");item.className="item";item.textContent=c.item;item.style.left=`${rand(10,78)}%`;item.style.top=`${rand(10,72)}%`;a.append(item);if(c.ttl)itemTimer=setTimeout(spawn,c.ttl)};spawn();const move=e=>{e.preventDefault();const p=pos(e,a);actor.style.left=`${clamp(p.x-27,0,a.clientWidth-54)}px`;actor.style.top=`${clamp(p.y-27,0,a.clientHeight-54)}px`;const r=actor.getBoundingClientRect(),q=item.getBoundingClientRect();if(r.left<q.right&&r.right>q.left&&r.top<q.bottom&&r.bottom>q.top){n++;$(".score",a).textContent=`${n}/${c.count}`;n>=c.count?complete():spawn()}};a.addEventListener("pointermove",move);a.addEventListener("pointerdown",move);cleanup=()=>{clearTimeout(itemTimer);a.removeEventListener("pointermove",move);a.removeEventListener("pointerdown",move)}},
 flight(a){let px=8,py=72,gulls=[],raf,start=performance.now();a.innerHTML+=`<div class="target" style="right:5%;top:7%">🏫</div><div class="actor" style="left:8%;top:72%">✈️</div>`;const plane=$(".actor",a),target=$(".target",a);for(let i=0;i<3;i++){const g=document.createElement("div");g.className="hazard gull";g.textContent="🪽";g.x=rand(15,80);g.y=rand(5,45);g.style.left=g.x+"%";g.style.top=g.y+"%";a.append(g);gulls.push(g)}const move=e=>{const p=pos(e,a);px=clamp((p.x-27)/a.clientWidth*100,0,86);py=clamp((p.y-27)/a.clientHeight*100,0,84)};a.addEventListener("pointermove",move);a.addEventListener("pointerdown",move);const loop=()=>{plane.style.left=px+"%";plane.style.top=py+"%";for(const g of gulls){g.x+=clamp(px-g.x,-.16,.16);g.y+=clamp(py-g.y,-.13,.13);g.style.left=g.x+"%";g.style.top=g.y+"%";const r=g.getBoundingClientRect(),q=plane.getBoundingClientRect();if(performance.now()-start>900&&r.left<q.right-12&&r.right>q.left+12&&r.top<q.bottom-12&&r.bottom>q.top+12)return fail("Gabbiano intercettore! Nuovo decollo.")}const r=plane.getBoundingClientRect(),q=target.getBoundingClientRect();if(r.left<q.right&&r.right>q.left&&r.top<q.bottom&&r.bottom>q.top)return complete();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);cleanup=()=>{cancelAnimationFrame(raf);a.removeEventListener("pointermove",move);a.removeEventListener("pointerdown",move)}},
 english(a){const rounds=[{q:"CASA",ok:"HOUSE",opts:["HOUSE","HORSE","MOUSE"]},{q:"CANE",ok:"DOG",opts:["CAT","DOG","DUCK"]},{q:"VIAGGIO",ok:"TRIP",opts:["TREE","TRIP","TRAIN"]}],box=document.createElement("div");box.className="english-game";a.append(box);let n=0;const show=()=>{const r=rounds[n];box.innerHTML=`<p>Come si dice <strong>${r.q}</strong>?</p><div>${r.opts.sort(()=>Math.random()-.5).map(x=>`<button>${x}</button>`).join("")}</div>`;box.querySelectorAll("button").forEach(b=>b.onclick=()=>{if(b.textContent===r.ok){n++;$(".score",a).textContent=`${n}/3`;n===3?complete():show()}else{b.classList.add("wrong");setTimeout(()=>b.classList.remove("wrong"),280);navigator.vibrate?.(25)}})};show();cleanup=()=>{}},
 aurora(a){let n=0;a.innerHTML+=`<img class="aurora-photo" src="assets/aurora.jpeg" alt="Aurora"><div class="aurora-cover"></div>`;const spawn=()=>{const b=document.createElement("button");b.className="tap-target baby-star";b.textContent="⭐";b.style.left=`${rand(8,78)}%`;b.style.top=`${rand(8,75)}%`;b.onclick=()=>{b.remove();n++;$(".score",a).textContent=`${n}/7`;$(".aurora-cover",a).style.opacity=String(1-n/7);if(n>=7){setTimeout(complete,1100)}else spawn()};a.append(b)};spawn();cleanup=()=>{}},
 dodge(a,c){let x=45,alive=0,items=[],start=performance.now(),raf;a.innerHTML+=`<div class="actor" style="left:45%;bottom:8%">${c.actor}</div>`;const actor=$(".actor",a);const move=e=>{x=clamp(pos(e,a).x/a.clientWidth*100,7,86)};a.addEventListener("pointermove",move);a.addEventListener("pointerdown",move);let last=0;const loop=t=>{actor.style.left=x+"%";if(t-last>520){last=t;const h=document.createElement("div");h.className="hazard";h.textContent=c.hazards[Math.floor(Math.random()*c.hazards.length)];h.x=rand(5,88);h.y=-40;h.style.left=h.x+"%";a.append(h);items.push(h)}for(const h of items){h.y+=3.5;h.style.top=h.y+"px";const r=h.getBoundingClientRect(),q=actor.getBoundingClientRect();if(r.left<q.right-10&&r.right>q.left+10&&r.top<q.bottom&&r.bottom>q.top)return fail("Collisione! Deb pretende il rematch.");if(h.y>a.clientHeight)h.remove()}items=items.filter(h=>h.isConnected);alive=(t-start)/1000;$(".score",a).textContent=`${Math.min(5,alive).toFixed(1)} / 5s`;if(alive>=5)return complete();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);cleanup=()=>{cancelAnimationFrame(raf);a.removeEventListener("pointermove",move);a.removeEventListener("pointerdown",move)}},
 timing(a){a.innerHTML+=`<div class="timing-track"><i class="sweet"></i><i class="needle"></i></div><button class="primary" style="position:absolute;bottom:12%;left:50%;transform:translateX(-50%)">STOP</button>`;let p=0,d=1,raf;const needle=$(".needle",a);const loop=()=>{p+=1.5*d;if(p>=98||p<=0)d*=-1;needle.style.left=p+"%";raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);$("button",a).onclick=()=>p>=39&&p<=58?complete():fail("Fuori asse. Un altro tentativo!");cleanup=()=>cancelAnimationFrame(raf)},
 memory(a,c){a.innerHTML=`<b class="score">0/3</b><div class="memory"></div>`;const values=[...c.pairs].sort(()=>Math.random()-.5),m=$(".memory",a);let open=[],done=0;values.forEach((v,i)=>{const b=document.createElement("button");b.dataset.v=v;b.textContent=v;b.onclick=()=>{if(open.length===2||b.classList.contains("done"))return;b.classList.add("open");open.push(b);if(open.length===2)setTimeout(()=>{const pair=Math.floor(c.pairs.indexOf(open[0].dataset.v)/2)===Math.floor(c.pairs.indexOf(open[1].dataset.v)/2)&&open[0]!==open[1];if(pair){open.forEach(x=>x.classList.add("done"));done++;$(".score",a).textContent=`${done}/3`;if(done===3)complete()}else open.forEach(x=>x.classList.remove("open"));open=[]},450)};m.append(b)});cleanup=()=>{}},
 find(a,c){const all=[c.target,...c.others].sort(()=>Math.random()-.5);a.innerHTML=`<div class="memory find-grid"></div>`;const grid=$(".find-grid",a);all.forEach((v,i)=>{const b=document.createElement("button");b.type="button";b.className="find-card open";b.dataset.correct=String(v===c.target);b.setAttribute("aria-label",v===c.target?`Trova ${c.target}`:`Carta ${i+1}`);b.textContent=v;grid.append(b)});const choose=e=>{e.preventDefault();const b=e.target.closest(".find-card");if(!b||locked)return;if(b.dataset.correct==="true"){b.classList.add("done");complete()}else{b.classList.add("wrong");navigator.vibrate?.(25);setTimeout(()=>b.classList.remove("wrong"),260)}};grid.addEventListener("pointerdown",choose);grid.addEventListener("touchstart",choose,{passive:false});cleanup=()=>{grid.removeEventListener("pointerdown",choose);grid.removeEventListener("touchstart",choose)}},
 maze(a){a.innerHTML+=`<div class="target" style="right:5%;top:8%">👩🏻‍❤️‍👨🏻</div><div class="actor" style="left:6%;bottom:8%">🐕</div>`;[[30,0,6,65],[62,35,6,65],[0,38,32,5],[62,68,38,5]].forEach(w=>a.insertAdjacentHTML("beforeend",`<i class="maze-wall" style="left:${w[0]}%;top:${w[1]}%;width:${w[2]}%;height:${w[3]}%"></i>`));games.drag(a,{a:"🐕",t:"👩🏻‍❤️‍👨🏻"})},
 balance(a){a.innerHTML+=`<div class="beam"></div><div class="balance-dot"></div>`;let tilt=0,hold=0,last=performance.now(),raf;const move=e=>{tilt+=(pos(e,a).x/a.clientWidth-.5)*8;tilt=clamp(tilt,-28,28)};a.addEventListener("pointermove",move);a.addEventListener("pointerdown",move);const loop=t=>{tilt+=rand(-1.5,1.5);tilt*=.96;$(".beam",a).style.transform=`rotate(${tilt}deg)`;$(".balance-dot",a).style.transform=`translateX(${tilt*3}px)`;hold+=(t-last)/1000;last=t;$(".score",a).textContent=`${Math.min(4,hold).toFixed(1)} / 4s`;if(Math.abs(tilt)>26)return fail("Equilibrio perso. Respira e riprova.");if(hold>=4)return complete();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);cleanup=()=>{cancelAnimationFrame(raf);a.removeEventListener("pointermove",move);a.removeEventListener("pointerdown",move)}},
 boss(a){let score=0,x=45,items=[],raf,last=0,start=performance.now();a.innerHTML+=`<div class="actor" style="left:45%;bottom:8%">😎</div>`;const actor=$(".actor",a),move=e=>x=clamp(pos(e,a).x/a.clientWidth*100,6,86);a.addEventListener("pointermove",move);a.addEventListener("pointerdown",move);const loop=t=>{actor.style.left=x+"%";if(t-last>430){last=t;const h=document.createElement("div"),good=Math.random()>.55;h.className="hazard";h.textContent=good?["💖","⭐","🦴"][Math.floor(rand(0,3))]:["🥦","🥕","🍎"][Math.floor(rand(0,3))];h.good=good;h.y=-35;h.style.left=rand(5,88)+"%";a.append(h);items.push(h)}for(const h of items){h.y+=4;h.style.top=h.y+"px";const r=h.getBoundingClientRect(),q=actor.getBoundingClientRect();if(r.left<q.right&&r.right>q.left&&r.top<q.bottom&&r.bottom>q.top){h.remove();if(h.good){score++;$(".score",a).textContent=`${score}/8`;if(score>=8)return complete()}else return fail("Broccolo critico! Boss reset.") }if(h.y>a.clientHeight)h.remove()}items=items.filter(h=>h.isConnected);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);cleanup=()=>{cancelAnimationFrame(raf);a.removeEventListener("pointermove",move);a.removeEventListener("pointerdown",move)}}
};
function finale(){screen.innerHTML=`<div class="final-card"><div class="big">🏆</div><p class="eyebrow">ALL STAGES CLEARED</p><h2>DEB — LEVEL 27<br>UNLOCKED</h2><p class="intro">Ventisette anni. Infinite vite extra.</p><h3 class="gift-question">Vuoi aprire il tuo regalo?</h3><button class="primary gift" data-gift>SÌ, APRILO</button><button class="text-btn" data-replay>PLAY AGAIN</button></div>`;confetti();$("[data-gift]").onclick=()=>{screen.insertAdjacentHTML("beforeend",`<div class="placeholder voucher-screen"><p class="eyebrow">PRESENT UNLOCKED</p><h2>Buon viaggio, Deb! ✈️</h2><img src="assets/voucher-alpitour-200.jpeg" alt="Buono regalo Alpitour da 200 euro" class="voucher-img"><a class="primary download-btn" href="assets/voucher-alpitour-200.jpeg" download="Buono-regalo-Deb-Alpitour-200.jpeg">SCARICA IL VOUCHER</a><button class="text-btn" data-close>INDIETRO</button></div>`);$("[data-close]").onclick=()=>$(".placeholder").remove()};$("[data-replay]").onclick=()=>{level=1;localStorage.setItem("deb27-level","1");render()}}
function confetti(){const colors=["#ff4f9a","#54e6da","#ffd45c","#7cf58c","#fff"];for(let i=0;i<70;i++){const c=document.createElement("i");c.className="confetti";c.style.left=rand(0,100)+"%";c.style.background=colors[i%colors.length];c.style.animationDuration=rand(2,4)+"s";c.style.animationDelay=rand(0,1.4)+"s";c.style.setProperty("--drift",rand(-80,80)+"px");screen.append(c)}}
screen.addEventListener("click",e=>{if(e.target.closest("[data-action=start]"))render();if(e.target.closest("[data-action=reset]")){if(confirm("Vuoi ricominciare dal livello 1?")){level=1;localStorage.removeItem("deb27-level");render()}}});
$("#homeBtn").onclick=menu;$("#restartBtn").onclick=()=>screen.querySelector(".arena")&&render();document.addEventListener("gesturestart",e=>e.preventDefault());menu();
